services:
  mysql:
    container_name: mysql_diary02  # 容器的名字
    restart: always  # 重启容器
    image: mysql:8.0.13  # 依赖的镜像
    environment:   # 环境的配置
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'root'
      MYSQL_PASS: '123456'
    ports:
      - 3306:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - "/home/cloud-diary/mysql-init:/docker-entrypoint-initdb.d"

  web:
    container_name: diary_web
    restart: always
    image: tomcat:9
    volumes:
      - "/home/cloud-diary/webapps/:/usr/local/tomcat/webapps/"
    ports:
      - 8080:8080
    links:
      - "mysql: mysql"